Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;
using KovsieCash_WebApp.Data;
using KovsieCash_WebApp.Models;
using Microsoft.AspNetCore.Identity;

namespace KovsieCash_WebApp.Controllers
{
    public class NotificationController : Controller
    {
        IRepositoryWrapper _repo;
        UserManager<ApplicationUser> _userManager;

        public NotificationController(IRepositoryWrapper repo, UserManager<ApplicationUser> userManager)
        {
            _repo = repo;
            _userManager = userManager;
        }

        public IActionResult List()
        {
            IEnumerable<Notification> notifications = _repo.Notifications.FindByCondition(n => n.UserID == _userManager.GetUserAsync(User).Result.Id);

            foreach (Notification _notification in notifications) 
            {
                if (_notification.Type != NotificationType.Advice && _notification.Type != NotificationType.RoleRequest)
                {
                    _notification.Status = NotificationStatus.Read;
                    _repo.Notifications.Update(_notification);

                }
            }

            _repo.Save();

            return View(notifications);
        }
    }
}

Controllers/TransactionController.cs
using KovsieCash_WebApp.Data;
using KovsieCash_WebApp.Models;
using KovsieCash_WebApp.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace KovsieCash_WebApp.Controllers
{
	public class TransactionController : Controller
	{
		private readonly IRepositoryWrapper _repo;
		private readonly UserManager<ApplicationUser> _userManager;
		public TransactionController(IRepositoryWrapper repo)
		{
			_repo = repo;
		}

		public IActionResult List(string id)
		{
			
			return View(_repo.Accounts.GetAccountWithHistory(id));
		}

		[HttpGet]
		public IActionResult Add(string id)
		{
			// Get the user ID from the claims
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

			// Retrieve accounts linked to the user
			IEnumerable<Account> accounts = _repo.Accounts.GetAccountsByUserId(userId);

			ViewBag.Accounts = accounts;

			// Pass the accounts to the view
			return View("Add", new TransferModel { TransferType = id });
		}

		[HttpPost]
		public IActionResult Add(TransferModel transfer)
		{
			_repo.Transactions.AddTransaction(transfer.fromAccNumber, transfer.toAccNumber, transfer.Amount, transfer.Reference);
			_repo.Save();

            return RedirectToAction("List", new { id = transfer.fromAccNumber });
        }
	}
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject IRepositoryWrapper _repo
@inject UserManager<ApplicationUser> UserManager

@{
    ApplicationUser currentUser = UserManager.GetUserAsync(User).Result;
    string userId = currentUser.Id;
    string profilePicture = currentUser?.ProfilePicture;
    IEnumerable<Notification> unreadNotifications = _repo.Notifications.FindByCondition(n => n.UserID == userId && n.Status == NotificationStatus.Unread);

}

@{
    string controller =
        ViewContext.RouteData.Values["controller"].ToString();
    string action =
        ViewContext.RouteData.Values["action"].ToString();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KovsieCash_WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KovsieCash_WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 px-1">
            <!-- Logo that is going to be used to navigate -->
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img width="200px" src="~/images/kovsie cash.png" />
            </a>

            <!-- Collapsable Navbar in case screen in small -->
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <nav class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarSupportedContent">
                <div class="navbar-nav me-auto">

                    <!-- Customer Nav Bar -->
                    @if (User.IsInRole("Customer"))
                    {
                        <!-- Transations DropDown -->
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Transact</a>
                           <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Transaction" asp-action="Add" asp-route-id="Transfer">Transfer</a>
                                <a class="dropdown-item" asp-controller="Transaction" asp-action="Add" asp-route-id="Pay">Pay</a>

                           </div>
                        </div>

                        <a class="nav-link
                        @(controller == "Review" && action == "Add" ? "active" : "")"
                           asp-controller="Review" asp-action="Add">
                            Home
                        </a>

                    }
                    <a class="nav-link
                        @(controller == "Home" && action == "About" ? "active" : "")"
                       asp-controller="Home" asp-action="About">About</a>
                </div>
                <ul class="navbar-nav navbar-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-link">
                            Hello, @User.Identity.Name
                            <img src="@Url.Content($"~/images/profilepictures/{profilePicture}")" alt="Profile Picture" style="width:50px; height:auto;  border-radius:50%;" />
                        </li>

                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link
                                @(controller.StartsWith("Admin") ? "active" : "")"
                                   asp-controller="AdminHome" asp-action="Index">Admin</a>
                            </li>
                        }

                        @if (unreadNotifications.Count() > 0)
                        {
                            <li class="nav-item me-2" style="margin-left:-10px">
                                <a class="nav-link position-relative" asp-controller="Notification" asp-action="List" asp-route-id="@userId">
                                    <p style="position: absolute; top: -5px; right: -10px; background-color: #0F204B; color: white; padding: 3px 6px; border-radius: 50%; font-size: 10px;">
                                        @unreadNotifications.Count()
                                    </p>
                                    <i class="fa-solid fa-bell fa-xl"></i>
                                </a>
                            </li>
                        }

                        <li class="nav-item mt-2">
                            <form asp-controller="Account" asp-action="Logout" method="post">

                                <button class="btn btn-link nav-link" type="submit"> <strong style="color:#A71930">Log Out</strong></button>

                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Log in</a>
                        </li>

                    }

                </ul>
            </nav>

        </nav>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer class="mt-2 px-3 " style="background-color:#A7A8AA">
        <div class="pt-2">
            <div class="row">
                <!-- Company Info -->
                <div class="col-lg-4 col-md-6">
                    <div class="mb-2 border-1 pt-3">
                        <p>205 Nelson Mandela Dr</p>
                        <p>Park West, Bloemfontein, 9301</p>
                        <p class="mt-3"><strong>Phone:</strong> <span>+27 51 401 3000 / 2525 / 9288</span></p>
                        <p><strong>Email:</strong> <span>studentadmin@ufs.ac.za</span></p>
                    </div>
                    <div class="d-flex mt-4" style="display:flex; gap:20px">
                        <a href="https://twitter.com/UFSweb?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="fa-brands fa-x-twitter fa-xl"></i></a>
                        <a href="https://www.facebook.com/UFSweb/"><i class="fa-brands fa-facebook-f fa-xl"></i></a>
                        <a href="https://www.instagram.com/ufsweb/"><i class="fa-brands fa-instagram fa-xl"></i></a>
                        <a href="https://www.linkedin.com/school/ufsweb/"><i class="fa-brands fa-linkedin-in fa-xl"></i></a>
                    </div>
                </div>

                <!-- Useful Links -->
                <div class="col-lg-2 col-md-3 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Terms of service</a></li>
                        <li><a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <!-- Our Services -->
                <div class="col-lg-2 col-md-3 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Web Development</a></li>
                        <li><a href="#">Product Management</a></li>
                        <li><a href="#">Marketing</a></li>
                        <li><a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <!-- Newsletter Form -->
                <div class="col-lg-4 col-md-12 footer-newsletter">
                    <h4>Our Newsletter</h4>
                    <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
                    <form action="forms/newsletter.php" method="post" class="php-email-form">
                        <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
                    </form>
                </div>
            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>© <span>Copyright</span> <strong class="px-1 sitename">KovsieCash</strong><span>All Rights Reserved</span></p>
            <div class="credits">
                Designed by <a href="https://tubatsekmoloi.wixsite.com/portfolio">Tubatse Katlego Moloi</a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>